blank_issues_enabled: false
contact_links:
  - name: "\U0000267F HMRC Digital Slack:#community-a11y"
    url: https://hmrcdigital.slack.com/archives/C4JQESR8U
    about: Ask questions, discuss issues and features, seek help.
